version: "2"

networks:
  test:

services:
  orderer0.consortiums.com:
    container_name: orderer0.consortiums.com #容器名
    extends: #引入base.yaml中定义的配置项
      file: base.yaml
      service: order-base
    volumes: #定义宿主机文件夹到容器中卷的映射关系
      - ../crypto-config/ordererOrganizations/consortiums.com/orderers/orderer0.consortiums.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/consortiums.com/orderers/orderer0.consortiums.com/tls/:/var/hyperledger/orderer/tls
    ports: # 定义宿主机端和容器中端口的映射关系
      - 7050:7050
      - 7053:7053
  orderer1.consortiums.com:
    container_name: orderer1.consortiums.com
    extends:
      file: base.yaml
      service: order-base
    volumes:
      - ../crypto-config/ordererOrganizations/consortiums.com/orderers/orderer1.consortiums.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/consortiums.com/orderers/orderer1.consortiums.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 8050:7050
      - 8053:7053
  orderer2.consortiums.com:
    container_name: orderer2.consortiums.com
    extends:
      file: base.yaml
      service: order-base
    volumes:
      - ../crypto-config/ordererOrganizations/consortiums.com/orderers/orderer2.consortiums.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/consortiums.com/orderers/orderer2.consortiums.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 9050:7050
      - 9053:7053
  orderer3.consortiums.com:
    container_name: orderer3.consortiums.com
    extends:
      file: base.yaml
      service: order-base
    volumes:
      - ../crypto-config/ordererOrganizations/consortiums.com/orderers/orderer3.consortiums.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/consortiums.com/orderers/orderer3.consortiums.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 10050:7050
      - 10053:7053
  orderer4.consortiums.com:
    container_name: orderer4.consortiums.com
    extends:
      file: base.yaml
      service: order-base
    volumes:
      - ../crypto-config/ordererOrganizations/consortiums.com/orderers/orderer4.consortiums.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/consortiums.com/orderers/orderer4.consortiums.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 11050:7050
      - 11053:7053

  peer0.org1.com:
    container_name: peer0.org1.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.com #Peer节点实例的标识ID
      - CORE_PEER_ADDRESS=peer0.org1.com:7051 #Peer节点的P2P连接地址
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051 #Peer节点的监听地址
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.com:7052 #链码连接该Peer节点的地址
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052 # Peer节点监听链码连接请求的地址
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.com:8051 #初始化gossip的引导节点列表
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.com:7051#向组织外节点发布的访问端点
      - CORE_PEER_LOCALMSPID=Org1MSP #本地MSP的标识ID
    volumes: #定义宿主机文件夹到容器中卷的映射关系
      - ../crypto-config/peerOrganizations/org1.com/peers/peer0.org1.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org1.com/peers/peer0.org1.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
  peer1.org1.com:
    container_name: peer1.org1.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.com
      - CORE_PEER_ADDRESS=peer1.org1.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.com:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ../crypto-config/peerOrganizations/org1.com/peers/peer1.org1.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org1.com/peers/peer1.org1.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:8051
      - 8052:8052

  peer0.org2.com:
    container_name: peer0.org2.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.com
      - CORE_PEER_ADDRESS=peer0.org2.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - ../crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:9051
      - 9052:9052

  peer1.org2.com:
    container_name: peer1.org2.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.com
      - CORE_PEER_ADDRESS=peer1.org2.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - ../crypto-config/peerOrganizations/org2.com/peers/peer1.org2.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org2.com/peers/peer1.org2.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:10051
      - 10052:10052

  cli-peer0-org1:
    container_name: cli-peer0-org1
    extends:
      file: base.yaml
      service: cli-base
    environment:
      - CORE_PEER_ID=cli-peer0-org1
      - CORE_PEER_ADDRESS=peer0.org1.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_CERT_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org1.com/peers/peer0.org1.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org1.com/peers/peer0.org1.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org1.com/peers/peer0.org1.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/hyperledger/opt/peer/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/msp

  cli-peer1-org1:
    container_name: cli-peer1-org1
    extends:
      file: base.yaml
      service: cli-base
    environment:
      - CORE_PEER_ID=cli-peer1-org1
      - CORE_PEER_ADDRESS=peer1.org1.com:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_CERT_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org1.com/peers/peer1.org1.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org1.com/peers/peer1.org1.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org1.com/peers/peer1.org1.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/hyperledger/opt/peer/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/msp

  cli-peer0-org2:
    container_name: cli-peer0-org2
    extends:
      file: base.yaml
      service: cli-base
    environment:
      - CORE_PEER_ID=cli-peer0-org2
      - CORE_PEER_ADDRESS=peer0.org2.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_TLS_CERT_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/hyperledger/opt/peer/crypto-config/peerOrganizations/org2.com/users/Admin@org2.com/msp

  cli-peer1-org2:
    container_name: cli-peer1-org2
    extends:
      file: base.yaml
      service: cli-base
    environment:
      - CORE_PEER_ID=cli-peer1-org2
      - CORE_PEER_ADDRESS=peer1.org2.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_TLS_CERT_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org2.com/peers/peer1.org2.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org2.com/peers/peer1.org2.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/hyperledger/opt/peer/crypto-config/peerOrganizations/org2.com/peers/peer1.org2.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/hyperledger/opt/peer/crypto-config/peerOrganizations/org2.com/users/Admin@org2.com/msp

  ca-org1:
    container_name: ca-org1
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/org1.com/ca:/etc/hyperledger/fabric-ca-server-config
  ca-org2:
    container_name: ca-org2
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - 8054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/org2.com/ca:/etc/hyperledger/fabric-ca-server-config
